# Generated by Django 2.2.3 on 2019-08-20 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_duration', models.CharField(max_length=200)),
                ('course_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[(1, 'COURSE'), (2, 'MONTHLY')], max_length=200)),
                ('status', models.CharField(choices=[(1, 'ACTIVE'), (0, 'Closed')], max_length=200)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('degree', models.CharField(choices=[('BCA', 'BCA'), ('BTECH', 'BTECH'), ('BSc', 'BSc'), ('MCA', 'MCA'), ('OTHER', 'OTHER')], max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='apply/image')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'FEMALE'), ('O', 'Other')], max_length=200)),
                ('contact', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_month', models.CharField(choices=[(1, 'JAN'), (2, 'FEB'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUG'), (9, 'SEP'), (10, 'OCT'), (11, 'NOV'), (12, 'DEC')], max_length=200)),
                ('p_amount', models.IntegerField()),
                ('p_due', models.IntegerField()),
                ('p_status', models.CharField(choices=[(1, 'Paid'), (2, 'Pending')], max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
