# Generated by Django 2.2.3 on 2019-08-24 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='data_of_join',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
