# Generated by Django 2.2.3 on 2019-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0002_studentcourse_data_of_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='p_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_month',
            field=models.CharField(choices=[('1', 'JAN'), ('2', 'FEB'), ('3', 'MARCH'), ('4', 'APRIL'), ('5', 'MAY'), ('6', 'JUNE'), ('7', 'JULY'), ('8', 'AUG'), ('9', 'SEP'), ('10', 'OCT'), ('11', 'NOV'), ('12', 'DEC')], max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_status',
            field=models.CharField(choices=[('1', 'Paid'), ('2', 'Pending')], max_length=200),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course_type',
            field=models.CharField(choices=[('1', 'COURSE'), ('2', 'MONTHLY')], max_length=200),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('1', 'ACTIVE'), ('0', 'Closed')], max_length=200),
        ),
    ]
