# Generated by Django 2.2.3 on 2019-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0003_auto_20190902_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='p_year',
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_month',
            field=models.DateTimeField(),
        ),
    ]
