# Generated by Django 2.2.3 on 2019-09-04 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0004_auto_20190902_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='p_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datawork.StudentCourse'),
        ),
    ]
