# Generated by Django 2.2.3 on 2019-09-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0005_payment_p_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Courseless'), ('3', 'takeout')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_status',
            field=models.CharField(choices=[('0', 'Not paid'), ('1', 'Pending'), ('2', 'Paid')], max_length=200),
        ),
    ]
