# Generated by Django 2.2.3 on 2019-10-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0006_auto_20190923_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='s_status',
            new_name='status',
        ),
    ]
