# Generated by Django 2.2.6 on 2019-10-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0007_auto_20191008_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slugs',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
